version: '3.7'

services:
  transactionstore.api:
    container_name: transactionstore.api
    build:
      context: .
      dockerfile: TransactionStore.Api/Dockerfile
    expose:
      - "80"
    ports:
      - "8491:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - db-engine
    links:
      - "db-engine"
    healthcheck:
      test: curl --fail -s http://localhost:80/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  db-engine:
    container_name: paymenttransactionsdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=paymenttransactionsdb
    ports:
      - "54302:5432"